<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Pasar;
use Illuminate\Support\Facades\DB;

class PasarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pasars = [
            ['kantor_cabang' => 'KANCAB BOGOR', 'kabupaten' => 'KABUPATEN BOGOR', 'nama_pasar' => 'PASAR CIMAYANG', 'latitude' => -6.607979, 'longitude' => 106.668038],
            ['kantor_cabang' => 'KANCAB BOGOR', 'kabupaten' => 'KABUPATEN BOGOR', 'nama_pasar' => 'PASAR CIAMPEA', 'latitude' => -6.551011, 'longitude' => 106.693455],
            ['kantor_cabang' => 'KANCAB BOGOR', 'kabupaten' => 'KABUPATEN BOGOR', 'nama_pasar' => 'PASAR CILUAR', 'latitude' => -6.544678, 'longitude' => 106.827274],
            ['kantor_cabang' => 'KANCAB BOGOR', 'kabupaten' => 'KABUPATEN BOGOR', 'nama_pasar' => 'PASAR CILEUNGSI', 'latitude' => -6.406842, 'longitude' => 106.962952],
            ['kantor_cabang' => 'KANCAB BOGOR', 'kabupaten' => 'KABUPATEN BOGOR', 'nama_pasar' => 'PASAR CIGUDEG', 'latitude' => -6.550872, 'longitude' => 106.534844],
            ['kantor_cabang' => 'KANCAB BOGOR', 'kabupaten' => 'KABUPATEN BOGOR', 'nama_pasar' => 'PASAR SALASA', 'latitude' => -6.6106157, 'longitude' => 106.6838398],
            ['kantor_cabang' => 'KANCAB CIANJUR', 'kabupaten' => 'KABUPATEN SUKABUMI', 'nama_pasar' => 'PASAR PELABUHAN RATU (SEMI MODERN)', 'latitude' => -6.986638, 'longitude' => 106.544824],
            ['kantor_cabang' => 'KANCAB CIANJUR', 'kabupaten' => 'KABUPATEN SUKABUMI', 'nama_pasar' => 'PASAR SUKARAJA', 'latitude' => -6.922353, 'longitude' => 106.973078],
            ['kantor_cabang' => 'KANCAB CIANJUR', 'kabupaten' => 'KABUPATEN SUKABUMI', 'nama_pasar' => 'PASAR CIBADAK', 'latitude' => -6.885733, 'longitude' => 106.779085],
            ['kantor_cabang' => 'KANCAB CIANJUR', 'kabupaten' => 'KABUPATEN SUKABUMI', 'nama_pasar' => 'PASAR PARUNG KUDA (SEMI MODERN)', 'latitude' => -6.821672, 'longitude' => 106.763707],
            ['kantor_cabang' => 'KANCAB CIANJUR', 'kabupaten' => 'KABUPATEN SUKABUMI', 'nama_pasar' => 'PASAR CIKEMBANG RAYA (SUKAMULYA)', 'latitude' => -6.945134, 'longitude' => 106.771902],
            ['kantor_cabang' => 'KANCAB CIANJUR', 'kabupaten' => 'KABUPATEN CIANJUR', 'nama_pasar' => 'PASAR INDUK CIANJUR', 'latitude' => -6.846705, 'longitude' => 107.134388],
            ['kantor_cabang' => 'KANCAB CIANJUR', 'kabupaten' => 'KABUPATEN CIANJUR', 'nama_pasar' => 'PASAR CIRANJANG', 'latitude' => -6.814017, 'longitude' => 107.250427],
            ['kantor_cabang' => 'KANCAB CIANJUR', 'kabupaten' => 'KABUPATEN CIANJUR', 'nama_pasar' => 'PASAR CIPANAS', 'latitude' => -6.730942, 'longitude' => 107.039808],
            ['kantor_cabang' => 'KANCAB CIANJUR', 'kabupaten' => 'KABUPATEN CIANJUR', 'nama_pasar' => 'PASAR MUKA CIANJUR', 'latitude' => -6.810995, 'longitude' => 107.147898],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KABUPATEN BANDUNG', 'nama_pasar' => 'PASAR BANJARAN', 'latitude' => -7.0487823, 'longitude' => 107.5851508],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KABUPATEN BANDUNG', 'nama_pasar' => 'PASAR SOREANG', 'latitude' => -7.028856, 'longitude' => 107.520438],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KABUPATEN BANDUNG', 'nama_pasar' => 'PASAR BARU CIBEUREUM', 'latitude' => -6.917675, 'longitude' => 107.603421],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KABUPATEN GARUT', 'nama_pasar' => 'PASAR PAJAGALAN MANDALAGIRI', 'latitude' => -7.213409, 'longitude' => 107.9031662],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KABUPATEN GARUT', 'nama_pasar' => 'PASAR DESA SIMPANG', 'latitude' => -7.2706476, 'longitude' => 107.8116875],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KABUPATEN GARUT', 'nama_pasar' => 'PASAR CIKAJANG', 'latitude' => -7.361543, 'longitude' => 107.811972],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KABUPATEN GARUT', 'nama_pasar' => 'PASAR ANDIR BAYONGBONG', 'latitude' => -7.26202754, 'longitude' => 107.8204623],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KABUPATEN GARUT', 'nama_pasar' => 'PASAR CISURUPAN', 'latitude' => -7.3097982, 'longitude' => 107.7915705],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KABUPATEN GARUT', 'nama_pasar' => 'PASAR SAMARANG', 'latitude' => -7.219869, 'longitude' => 107.839129],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KABUPATEN GARUT', 'nama_pasar' => 'PASAR GUNTUR', 'latitude' => -7.201655, 'longitude' => 107.90426],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KABUPATEN GARUT', 'nama_pasar' => 'PASAR CIMURAH', 'latitude' => -7.2032007, 'longitude' => 107.9521492],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KABUPATEN GARUT', 'nama_pasar' => 'PASAR WANARAJA', 'latitude' => -7.1753178, 'longitude' => 107.9802679],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KABUPATEN GARUT', 'nama_pasar' => 'PASAR LELES', 'latitude' => -7.112108, 'longitude' => 107.89825],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KABUPATEN GARUT', 'nama_pasar' => 'PASAR KADUNGORA', 'latitude' => -7.075386, 'longitude' => 107.91531],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KABUPATEN GARUT', 'nama_pasar' => 'PASAR CILIMUS', 'latitude' => -7.260838, 'longitude' => 107.855456],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KABUPATEN GARUT', 'nama_pasar' => 'PASAR CIBODAS', 'latitude' => -7.23743987, 'longitude' => 107.8325851],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KABUPATEN TASIKMALAYA', 'nama_pasar' => 'PASAR TARAJU', 'latitude' => -7.4589008, 'longitude' => 107.9777175],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KABUPATEN CIAMIS', 'nama_pasar' => 'PASAR MANIS CIAMIS', 'latitude' => -7.33208, 'longitude' => 108.358953],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KABUPATEN KUNINGAN', 'nama_pasar' => 'PASAR ANCARAN', 'latitude' => -6.97115, 'longitude' => 108.51682],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KABUPATEN KUNINGAN', 'nama_pasar' => 'PASAR DESA CIPUTAT', 'latitude' => -6.977452, 'longitude' => 108.576928],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KABUPATEN KUNINGAN', 'nama_pasar' => 'PASAR BARU', 'latitude' => -6.9826688, 'longitude' => 108.481406],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KABUPATEN KUNINGAN', 'nama_pasar' => 'PASAR CIAWIGEBANG', 'latitude' => -6.969666, 'longitude' => 108.575626],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KABUPATEN CIREBON', 'nama_pasar' => 'PASAR DURAJAYA', 'latitude' => -6.824706, 'longitude' => 108.53019],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KABUPATEN CIREBON', 'nama_pasar' => 'PASAR DESA SAMPIRAN', 'latitude' => -6.770724, 'longitude' => 108.510293],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KABUPATEN CIREBON', 'nama_pasar' => 'PASAR SUMBER', 'latitude' => -6.760681, 'longitude' => 108.485566],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KABUPATEN CIREBON', 'nama_pasar' => 'PASAR PALIMANAN', 'latitude' => -6.71063, 'longitude' => 108.437864],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KABUPATEN CIREBON', 'nama_pasar' => 'PASAR JAMBLANG', 'latitude' => -6.708313, 'longitude' => 108.454528],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KABUPATEN CIREBON', 'nama_pasar' => 'PASAR DESA CELANCANG', 'latitude' => -6.649766, 'longitude' => 108.531566],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KABUPATEN CIREBON', 'nama_pasar' => 'PASAR DESA GEBANG MEKAR', 'latitude' => -6.832366, 'longitude' => 108.725385],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KABUPATEN CIREBON', 'nama_pasar' => 'PASAR DESA ARJAWINANGUN', 'latitude' => -6.64296, 'longitude' => 108.402231],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KABUPATEN CIREBON', 'nama_pasar' => 'PASAR PASALARAN', 'latitude' => -6.704723, 'longitude' => 108.506346],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KABUPATEN CIREBON', 'nama_pasar' => 'PASAR DESA LEMAHABANG KULON', 'latitude' => -6.8283, 'longitude' => 108.628608],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KABUPATEN CIREBON', 'nama_pasar' => 'PASAR KARANGARI', 'latitude' => -6.725136, 'longitude' => 108.485263],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KABUPATEN SUMEDANG', 'nama_pasar' => 'PASAR INPRES', 'latitude' => -6.846643, 'longitude' => 107.926346],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR DAERAH HAURGEULIS', 'latitude' => -6.4651431, 'longitude' => 107.9371798],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR DESA CIKEDUNG', 'latitude' => -6.486869, 'longitude' => 108.181209],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR DESA TUNGGUL PAYUNG / PASAR TUGU', 'latitude' => -6.511702, 'longitude' => 108.21033],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR DESA TUKDANA/PASAR ASSAKINAH', 'latitude' => -6.547078, 'longitude' => 108.285634],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR DESA TULUNGAGUNG', 'latitude' => -6.534316, 'longitude' => 108.352541],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR DAERAH BONDAN', 'latitude' => -6.596149, 'longitude' => 108.297737],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR DAERAH SINGAKERTA', 'latitude' => -6.542261, 'longitude' => 108.495422],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR BARU', 'latitude' => -6.34173, 'longitude' => 108.330096],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR DESA KEDOKAN AGUNG', 'latitude' => -6.500742, 'longitude' => 108.427077],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR DAERAH JATIBARANG', 'latitude' => -6.468583, 'longitude' => 108.311567],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR DAERAHKANDANGHAUR', 'latitude' => -6.372111, 'longitude' => 108.1233],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR KEDUNGWUNGU', 'latitude' => -6.415273, 'longitude' => 107.957825],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR DAERAH SUKRA', 'latitude' => -6.305414, 'longitude' => 107.934694],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR DAERAH PATROL', 'latitude' => -6.314674, 'longitude' => 107.991341],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR DESA GABUSWETAN', 'latitude' => -6.422411, 'longitude' => 108.079295],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR DESA LELEA', 'latitude' => -6.420044, 'longitude' => 108.253657],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR ERETAN WETAN', 'latitude' => -6.354748, 'longitude' => 108.106586],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR HEWAN WANGUK', 'latitude' => -6.4152853, 'longitude' => 107.9578141],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR BUGEL', 'latitude' => -6.315533, 'longitude' => 108.008997],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR HEWAN KARANGAMPEL', 'latitude' => -6.456461, 'longitude' => 108.447858],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR BANGKIR', 'latitude' => -6.378254, 'longitude' => 108.292348],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR DESA BUGIS', 'latitude' => -6.389992, 'longitude' => 107.929129],
            ['kantor_cabang' => 'KANCAB SUBANG', 'kabupaten' => 'KABUPATEN SUBANG', 'nama_pasar' => 'PASAR PUJASERA SUBANG', 'latitude' => -6.568486, 'longitude' => 107.757535],
            ['kantor_cabang' => 'KANCAB SUBANG', 'kabupaten' => 'KABUPATEN SUBANG', 'nama_pasar' => 'PASAR KALIJATI', 'latitude' => -6.3132556, 'longitude' => 107.4027954],
            ['kantor_cabang' => 'KANCAB SUBANG', 'kabupaten' => 'KABUPATEN SUBANG', 'nama_pasar' => 'PASAR CIPEUNDEUY', 'latitude' => -6.301017, 'longitude' => 107.349534],
            ['kantor_cabang' => 'KANCAB SUBANG', 'kabupaten' => 'KABUPATEN SUBANG', 'nama_pasar' => 'PASAR PABUARAN', 'latitude' => -6.410437, 'longitude' => 107.5836828],
            ['kantor_cabang' => 'KANCAB SUBANG', 'kabupaten' => 'KABUPATEN SUBANG', 'nama_pasar' => 'PASAR PURWADADI', 'latitude' => -6.4495, 'longitude' => 107.6861],
            ['kantor_cabang' => 'KANCAB SUBANG', 'kabupaten' => 'KABUPATEN SUBANG', 'nama_pasar' => 'PASAR PAGADEN INPRES', 'latitude' => -6.45674, 'longitude' => 107.817692],
            ['kantor_cabang' => 'KANCAB SUBANG', 'kabupaten' => 'KABUPATEN SUBANG', 'nama_pasar' => 'PASAR WATES', 'latitude' => -6.381245, 'longitude' => 107.797618],
            ['kantor_cabang' => 'KANCAB SUBANG', 'kabupaten' => 'KABUPATEN SUBANG', 'nama_pasar' => 'PASAR CIASEM', 'latitude' => -6.332806, 'longitude' => 107.675683],
            ['kantor_cabang' => 'KANCAB SUBANG', 'kabupaten' => 'KABUPATEN SUBANG', 'nama_pasar' => 'PASAR INPRES PAMANUKAN', 'latitude' => -6.270037, 'longitude' => 107.879002],
            ['kantor_cabang' => 'KANCAB SUBANG', 'kabupaten' => 'KABUPATEN SUBANG', 'nama_pasar' => 'PASAR PUSAKAJAYA', 'latitude' => -6.303836, 'longitude' => 107.920084],
            ['kantor_cabang' => 'KANCAB SUBANG', 'kabupaten' => 'KABUPATEN SUBANG', 'nama_pasar' => 'PASAR BOBOS', 'latitude' => -6.269549, 'longitude' => 107.82022],
            ['kantor_cabang' => 'KANCAB SUBANG', 'kabupaten' => 'KABUPATEN SUBANG', 'nama_pasar' => 'PASAR BLANAKAN', 'latitude' => -6.259971, 'longitude' => 107.621194],
            ['kantor_cabang' => 'KANCAB SUBANG', 'kabupaten' => 'KABUPATEN SUBANG', 'nama_pasar' => 'PASAR SUKAMANDI', 'latitude' => -6.349421, 'longitude' => 107.659194],
            ['kantor_cabang' => 'KANCAB SUBANG', 'kabupaten' => 'KABUPATEN SUBANG', 'nama_pasar' => 'PASAR RAKYAT', 'latitude' => -6.549274, 'longitude' => 107.76984],
            ['kantor_cabang' => 'KANCAB SUBANG', 'kabupaten' => 'KABUPATEN PURWAKARTA', 'nama_pasar' => 'PASAR CITEKO', 'latitude' => -6.426367, 'longitude' => 107.482856],
            ['kantor_cabang' => 'KANCAB SUBANG', 'kabupaten' => 'KABUPATEN PURWAKARTA', 'nama_pasar' => 'PASAR ANYAR SUKATANI', 'latitude' => -6.609014, 'longitude' => 107.412616],
            ['kantor_cabang' => 'KANCAB SUBANG', 'kabupaten' => 'KABUPATEN PURWAKARTA', 'nama_pasar' => 'PASAR WANAYASA', 'latitude' => -6.680452, 'longitude' => 107.555387],
            ['kantor_cabang' => 'KANCAB SUBANG', 'kabupaten' => 'KABUPATEN PURWAKARTA', 'nama_pasar' => 'PASAR REBO', 'latitude' => -6.565453, 'longitude' => 107.451857],
            ['kantor_cabang' => 'KANCAB SUBANG', 'kabupaten' => 'KABUPATEN PURWAKARTA', 'nama_pasar' => 'PASAR LEUWI PANJANG', 'latitude' => -6.541652, 'longitude' => 107.437609],
            ['kantor_cabang' => 'KANCAB KARAWANG', 'kabupaten' => 'KABUPATEN KARAWANG', 'nama_pasar' => 'PASAR CIKAMPEK III', 'latitude' => -6.40888043, 'longitude' => 107.4594973],
            ['kantor_cabang' => 'KANCAB BOGOR', 'kabupaten' => 'KOTA BOGOR', 'nama_pasar' => 'PD PASAR PAKUAN/PASAR KEBUN KEMBANG', 'latitude' => -6.591074, 'longitude' => 106.792716],
            ['kantor_cabang' => 'KANCAB BOGOR', 'kabupaten' => 'KOTA BOGOR', 'nama_pasar' => 'PASAR TANAH BARU', 'latitude' => -6.583022, 'longitude' => 106.821907],
            ['kantor_cabang' => 'KANCAB BOGOR', 'kabupaten' => 'KOTA BOGOR', 'nama_pasar' => 'PASAR BARU BOGOR', 'latitude' => -6.603527, 'longitude' => 106.801002],
            ['kantor_cabang' => 'KANCAB CIANJUR', 'kabupaten' => 'KOTA SUKABUMI', 'nama_pasar' => 'UPTD. PASAR TIPAR GEDE', 'latitude' => -6.925531, 'longitude' => 106.929501],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KOTA BANDUNG', 'nama_pasar' => 'PASAR GEDE BAGE', 'latitude' => -6.935149, 'longitude' => 107.698373],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KOTA BANDUNG', 'nama_pasar' => 'PASAR KIARACONDONG', 'latitude' => -6.92646, 'longitude' => 107.644994],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KOTA BANDUNG', 'nama_pasar' => 'PASAR INDUK CARINGIN', 'latitude' => -6.9427232, 'longitude' => 107.5766961],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KOTA BANDUNG', 'nama_pasar' => 'PASAR KOSAMBI', 'latitude' => -6.919204, 'longitude' => 107.622373],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KOTA BANDUNG', 'nama_pasar' => 'PASAR GEGERKALONG', 'latitude' => -6.867509, 'longitude' => 107.591565],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KOTA BANDUNG', 'nama_pasar' => 'PASAR SEDERHANA / BERMARTABAT', 'latitude' => -6.890298, 'longitude' => 107.599533],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KOTA BANDUNG', 'nama_pasar' => 'PASAR ASTANA ANYAR', 'latitude' => -6.9118195, 'longitude' => 107.7153623],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KOTA BANDUNG', 'nama_pasar' => 'PASAR ANCOL KARAPITAN', 'latitude' => -6.932506, 'longitude' => 107.615769],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KOTA CIREBON', 'nama_pasar' => 'PASAR PUSAT PERDAGANGAN HARJAMUKTI', 'latitude' => -6.745452, 'longitude' => 108.542175],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KOTA CIREBON', 'nama_pasar' => 'PASAR JAGASATRU', 'latitude' => -6.726709, 'longitude' => 108.564392],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KOTA CIREBON', 'nama_pasar' => 'PASAR PAGI', 'latitude' => -6.712594, 'longitude' => 108.560849],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KOTA CIREBON', 'nama_pasar' => 'PASAR PERUMNAS', 'latitude' => -6.747335, 'longitude' => 108.561323],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KOTA CIREBON', 'nama_pasar' => 'PASAR DRAJAT', 'latitude' => -6.7353, 'longitude' => 108.560074],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KOTA CIREBON', 'nama_pasar' => 'PASAR GUNUNG SARI', 'latitude' => -6.712976, 'longitude' => 108.550583],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KOTA CIMAHI', 'nama_pasar' => 'PASAR CIMINDI RAYA', 'latitude' => -6.8731527, 'longitude' => 107.5423099],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KOTA CIMAHI', 'nama_pasar' => 'PASAR ATAS BARU', 'latitude' => -6.869241, 'longitude' => 107.542664],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KOTA TASIKMALAYA', 'nama_pasar' => 'PASAR PANCASILA', 'latitude' => -7.326074, 'longitude' => 108.228984],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KOTA TASIKMALAYA', 'nama_pasar' => 'PASAR CIKURUBUK', 'latitude' => -7.3371859, 'longitude' => 108.2016079],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KOTA BANJAR', 'nama_pasar' => 'PASAR BANJAR', 'latitude' => -7.374423, 'longitude' => 108.548216],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KABUPATEN BANDUNG', 'nama_pasar' => 'PASAR WANGISAGARA', 'latitude' => -7.0760634, 'longitude' => 107.7373365],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KABUPATEN SUMEDANG', 'nama_pasar' => 'PASAR HEGARMANAH', 'latitude' => -6.9247059, 'longitude' => 107.7642853],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KABUPATEN BANDUNG', 'nama_pasar' => 'PASAR BALEENDAH', 'latitude' => -7.0001047, 'longitude' => 107.6239938],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KABUPATEN BANDUNG', 'nama_pasar' => 'PASAR MAJALAYA', 'latitude' => -7.0000975, 'longitude' => 107.5441666],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KABUPATEN SUMEDANG', 'nama_pasar' => 'PASAR PARAKAN MUNCANG', 'latitude' => -6.96435, 'longitude' => 107.82703],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KABUPATEN SUMEDANG', 'nama_pasar' => 'PASAR SITURAJA', 'latitude' => -6.8399064, 'longitude' => 107.9329433],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KOTA BANDUNG', 'nama_pasar' => 'PASAR SUKAHAJI', 'latitude' => -6.9276506, 'longitude' => 107.5832779],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KOTA CIMAHI', 'nama_pasar' => 'PASAR RANCA BENTANG', 'latitude' => -6.9053713, 'longitude' => 107.5563777],
            ['kantor_cabang' => 'KANCAB KARAWANG', 'kabupaten' => 'KABUPATEN KARAWANG', 'nama_pasar' => 'PASAR JOHAR', 'latitude' => -6.313043, 'longitude' => 107.314868],
            ['kantor_cabang' => 'KANCAB KARAWANG', 'kabupaten' => 'KABUPATEN KARAWANG', 'nama_pasar' => 'PASAR BARU KARAWANG', 'latitude' => -6.308925, 'longitude' => 107.295195],
            ['kantor_cabang' => 'KANCAB KARAWANG', 'kabupaten' => 'KABUPATEN BEKASI', 'nama_pasar' => 'PASAR TAMBUN', 'latitude' => -6.261341, 'longitude' => 107.055481],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KABUPATEN KUNINGAN', 'nama_pasar' => 'PASAR DESA DARMA', 'latitude' => -7.002191, 'longitude' => 108.403446],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KOTA CIREBON', 'nama_pasar' => 'PASAR KRAMAT', 'latitude' => -6.70117, 'longitude' => 108.55599],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KABUPATEN PANGANDARAN', 'nama_pasar' => 'PASAR PARIGI', 'latitude' => -7.69551, 'longitude' => 108.50134],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KABUPATEN PANGANDARAN', 'nama_pasar' => 'PASAR PANANJUNG-PANGANDARAN', 'latitude' => -7.6840096, 'longitude' => 108.6479144],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KABUPATEN PANGANDARAN', 'nama_pasar' => 'PASAR CIKEMBULAN', 'latitude' => -7.675792, 'longitude' => 108.614972],
            ['kantor_cabang' => 'KANCAB CIANJUR', 'kabupaten' => 'KABUPATEN SUKABUMI', 'nama_pasar' => 'PASAR CICURUG', 'latitude' => -6.786604, 'longitude' => 106.781237],
            ['kantor_cabang' => 'KANCAB KARAWANG', 'kabupaten' => 'KOTA BEKASI', 'nama_pasar' => 'PASAR KRANGGAN', 'latitude' => -6.364014, 'longitude' => 106.923563],
            ['kantor_cabang' => 'KANCAB KARAWANG', 'kabupaten' => 'KOTA BEKASI', 'nama_pasar' => 'PASAR BARU BEKASI', 'latitude' => -6.246619, 'longitude' => 107.013966],
            ['kantor_cabang' => 'KANCAB KARAWANG', 'kabupaten' => 'KABUPATEN KARAWANG', 'nama_pasar' => 'PASAR CILAMAYA', 'latitude' => -6.319487, 'longitude' => 107.56136],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KOTA TASIKMALAYA', 'nama_pasar' => 'PASAR INDIHIANG', 'latitude' => -7.289351, 'longitude' => 108.193331],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KABUPATEN SUMEDANG', 'nama_pasar' => 'PASAR TANJUNG SARI', 'latitude' => -6.9078, 'longitude' => 107.797198],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KABUPATEN GARUT', 'nama_pasar' => 'PASAR DESA CIBATU', 'latitude' => -7.091651, 'longitude' => 107.983045],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR DAERAH INDRAMAYU', 'latitude' => -6.341606, 'longitude' => 108.330084],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KABUPATEN KUNINGAN', 'nama_pasar' => 'PASAR KEPUH', 'latitude' => -6.981672, 'longitude' => 108.480464],
            ['kantor_cabang' => 'KANCAB KARAWANG', 'kabupaten' => 'KOTA BEKASI', 'nama_pasar' => 'PASAR BANTAR GEBANG', 'latitude' => -6.313491, 'longitude' => 106.987348],
            ['kantor_cabang' => 'KANCAB KARAWANG', 'kabupaten' => 'KOTA BEKASI', 'nama_pasar' => 'PASAR BARU JATI ASIH', 'latitude' => -6.290572, 'longitude' => 106.966693],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KOTA BANDUNG', 'nama_pasar' => 'PASAR RECOK', 'latitude' => -6.929407, 'longitude' => 107.558576],
            ['kantor_cabang' => 'KANCAB KARAWANG', 'kabupaten' => 'KOTA BEKASI', 'nama_pasar' => 'PASAR WISMA JAYA', 'latitude' => -6.233949, 'longitude' => 107.031561],
            ['kantor_cabang' => 'KANCAB CIANJUR', 'kabupaten' => 'KABUPATEN SUKABUMI', 'nama_pasar' => 'PASAR CISAAT (SEMI MODERN)', 'latitude' => -6.905614, 'longitude' => 106.893668],
            ['kantor_cabang' => 'KANCAB BOGOR', 'kabupaten' => 'KABUPATEN BOGOR', 'nama_pasar' => 'PASAR CISEENG', 'latitude' => -6.449577, 'longitude' => 106.699075],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KABUPATEN TASIKMALAYA', 'nama_pasar' => 'PASAR CIAWI', 'latitude' => -7.1559378, 'longitude' => 108.1507583],
            ['kantor_cabang' => 'KANCAB CIANJUR', 'kabupaten' => 'KOTA SUKABUMI', 'nama_pasar' => 'PASAR PELITA / STASIUN TIMUR', 'latitude' => -6.924184, 'longitude' => 106.928854],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KOTA BANDUNG', 'nama_pasar' => 'PASAR SADANG SERANG', 'latitude' => -6.891737, 'longitude' => 107.624869],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KOTA BANDUNG', 'nama_pasar' => 'PASAR BALUBUR', 'latitude' => -6.889, 'longitude' => 107.608774],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR TEMIYANG', 'latitude' => -6.4688065, 'longitude' => 108.016725],
            ['kantor_cabang' => 'KANCAB INDRAMAYU', 'kabupaten' => 'KABUPATEN INDRAMAYU', 'nama_pasar' => 'PASAR DESA KEDOKANGABUS', 'latitude' => -6.4653239, 'longitude' => 108.1043814],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KABUPATEN BANDUNG', 'nama_pasar' => 'PASAR SWAMANDIRI DIMENSI', 'latitude' => -6.93185, 'longitude' => 107.5392117],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KABUPATEN MAJALENGKA', 'nama_pasar' => 'PASAR PEMDA KADIPATEN', 'latitude' => -6.766406, 'longitude' => 108.168478],
            ['kantor_cabang' => 'KANCAB CIAMIS', 'kabupaten' => 'KABUPATEN TASIKMALAYA', 'nama_pasar' => 'PASAR SINGAPARNA', 'latitude' => -7.351508, 'longitude' => 108.111189],
            ['kantor_cabang' => 'KANCAB CIREBON', 'kabupaten' => 'KABUPATEN MAJALENGKA', 'nama_pasar' => 'PASAR PEMDA SINDANG KASIH', 'latitude' => -6.83266, 'longitude' => 108.250931],
            ['kantor_cabang' => 'KANCAB BOGOR', 'kabupaten' => 'KOTA DEPOK', 'nama_pasar' => 'PASAR KEMIRIMUKA', 'latitude' => -6.386642, 'longitude' => 106.824404],
            ['kantor_cabang' => 'KANCAB BOGOR', 'kabupaten' => 'KOTA DEPOK', 'nama_pasar' => 'PASAR AGUNG', 'latitude' => -6.392322, 'longitude' => 106.845647],
            ['kantor_cabang' => 'KANCAB BOGOR', 'kabupaten' => 'KOTA DEPOK', 'nama_pasar' => 'PASAR CISALAK', 'latitude' => -6.377901, 'longitude' => 106.868034],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KABUPATEN BANDUNG BARAT', 'nama_pasar' => 'PASAR TAGOG PADALARANG', 'latitude' => -6.840776, 'longitude' => 107.485934],
            ['kantor_cabang' => 'KANCAB KARAWANG', 'kabupaten' => 'KABUPATEN BEKASI', 'nama_pasar' => 'PASAR KEDUNGGEDE', 'latitude' => -6.272327, 'longitude' => 107.266202],
            ['kantor_cabang' => 'KANCAB BANDUNG', 'kabupaten' => 'KOTA BANDUNG', 'nama_pasar' => 'PASAR CIBOGO', 'latitude' => -6.8840173, 'longitude' => 107.5749629],
            ['kantor_cabang' => 'KANCAB BOGOR', 'kabupaten' => 'KABUPATEN BOGOR', 'nama_pasar' => 'PASAR CIBINONG', 'latitude' => -6.4665122, 'longitude' => 106.8529681]
        ];

        foreach ($pasars as $pasar) {
            Pasar::create($pasar);
        }
    }
}
